networks:
  backend:
    name: "${COMPOSE_PROJECT_NAME}"

services:
  nginx:
    container_name: "${COMPOSE_PROJECT_NAME}.nginx"
    build:
      context: "../../docker/nginx"
      target: "local"
    image: "chatapp/nginx"
    ports:
      - "${WEB_PORT}:80"
    volumes:
      - "../../src:/var/www:cached"
    depends_on:
      - "php-fpm"
    networks:
      - "backend"

  mysql:
    container_name: "${COMPOSE_PROJECT_NAME}.mysql"
    image: 'mysql/mysql-server:8.0'
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - 'mysql:/var/lib/mysql'
      - './mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh' # copy from sail
    networks:
      - "backend"
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - '-p${DB_PASSWORD}'
      retries: 3
      timeout: 5s

  php-fpm:
    container_name: "${COMPOSE_PROJECT_NAME}.php-fpm"
    build:
      context: "../../docker/php-fpm"
      target: "local"
    image: "chatapp/php-fpm"
    volumes:
      - ../../src:/var/www:cached
      - ../../api:/var/www/api:cached
      - ./my-php.ini:/usr/local/etc/php/conf.d/my-php.ini
    environment:
      TZ: "Asia/Tokyo"
    networks:
      - "backend"

  minio:
    container_name: "${COMPOSE_PROJECT_NAME}.minio"
    image: "minio/minio:latest"
    environment:
      MINIO_ROOT_USER: "asdfghASDFGH"
      MINIO_ROOT_PASSWORD: "asdfgh123456"
    entrypoint: "bash"
    command: '-c "minio server /data --address :9000 --console-address :9001"'
    volumes:
      - "minio:/data"
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - "backend"

  mailpit:
    container_name: "${COMPOSE_PROJECT_NAME}.${APP_ENV}.mailpit"
    image: "axllent/mailpit:v1.9"
    ports:
      - "${FORWARD_MAILPIT_PORT:-1025}:1025"
      - "${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025"
    environment:
      TZ: "Asia/Tokyo"
    networks:
      - "backend"

  redis:
    container_name: "${COMPOSE_PROJECT_NAME}.redis"
    image: 'redis:alpine'
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - 'redis:/data'
    networks:
      - "backend"
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      retries: 3
      timeout: 5s

volumes:
  mysql:
    driver: local
  minio:
    driver: local
  redis:
    driver: local
